import { Expert, BusinessOwner, Project, Application, Quote, MajayoungCash, CashTransaction, CashPackage, PaymentMethod } from '@/types';

export const experts: Expert[] = [
  {
    id: '1',
    name: '김마케팅',
    email: 'marketing.kim@email.com',
    phone: '010-1234-5678',
    userType: 'expert',
    expertise: ['SNS 마케팅', '브랜딩', '광고 기획'],
    experience: 5,
    rating: 4.8,
    completedProjects: 32,
    hourlyRate: 50000,
    bio: '5년간 다양한 브랜드의 마케팅을 담당했으며, 특히 소규모 자영업체의 온라인 마케팅 전략 수립에 전문성을 가지고 있습니다.',
    portfolio: ['카페 브랜딩 프로젝트', '온라인 쇼핑몰 마케팅'],
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: '박디지털',
    email: 'digital.park@email.com',
    phone: '010-2345-6789',
    userType: 'expert',
    expertise: ['디지털 마케팅', '구글 광고', '네이버 광고'],
    experience: 3,
    rating: 4.6,
    completedProjects: 18,
    hourlyRate: 45000,
    bio: '디지털 마케팅 전문가로 구글, 네이버 광고 운영에 특화되어 있습니다.',
    portfolio: ['음식점 온라인 광고', '뷰티샵 디지털 마케팅'],
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: '이콘텐츠',
    email: 'content.lee@email.com',
    phone: '010-3456-7890',
    userType: 'expert',
    expertise: ['콘텐츠 마케팅', '블로그 마케팅', 'SEO'],
    experience: 4,
    rating: 4.9,
    completedProjects: 25,
    hourlyRate: 40000,
    bio: '콘텐츠 마케팅과 SEO 전문가로 검색 엔진 최적화를 통한 자연스러운 마케팅을 지향합니다.',
    portfolio: ['헬스장 블로그 마케팅', '펜션 SEO 최적화'],
    createdAt: '2024-01-30',
  },
  {
    id: '4',
    name: '최소셜',
    email: 'social.choi@email.com',
    phone: '010-4567-8901',
    userType: 'expert',
    expertise: ['인스타그램 마케팅', '틱톡 마케팅', '인플루언서 마케팅'],
    experience: 2,
    rating: 4.5,
    completedProjects: 12,
    hourlyRate: 35000,
    bio: '소셜미디어 마케팅 전문가로 젊은 층을 타겟으로 하는 마케팅에 특화되어 있습니다.',
    portfolio: ['패션샵 인스타그램', '카페 틱톡 마케팅'],
    createdAt: '2024-03-10',
  },
  {
    id: '5',
    name: '정전략',
    email: 'strategy.jung@email.com',
    phone: '010-5678-9012',
    userType: 'expert',
    expertise: ['마케팅 전략', '브랜드 컨설팅', '시장 분석'],
    experience: 7,
    rating: 5.0,
    completedProjects: 45,
    hourlyRate: 70000,
    bio: '마케팅 전략 컨설턴트로 브랜드의 전반적인 마케팅 방향성을 설정하는 데 전문성을 가지고 있습니다.',
    portfolio: ['프랜차이즈 마케팅 전략', '스타트업 브랜딩'],
    createdAt: '2024-01-05',
  },
];

export const businessOwners: BusinessOwner[] = [
  {
    id: '1',
    name: '홍길동',
    email: 'hong@cafe.com',
    phone: '010-1111-2222',
    userType: 'business',
    businessName: '홍대 원두카페',
    businessType: '카페/음료',
    location: '서울시 마포구',
    createdAt: '2024-01-10',
  },
  {
    id: '2',
    name: '김영희',
    email: 'kim@beauty.com',
    phone: '010-3333-4444',
    userType: 'business',
    businessName: '영희네 뷰티샵',
    businessType: '미용/뷰티',
    location: '부산시 해운대구',
    createdAt: '2024-02-15',
  },
  {
    id: '3',
    name: '박철수',
    email: 'park@restaurant.com',
    phone: '010-5555-6666',
    userType: 'business',
    businessName: '철수네 한식당',
    businessType: '음식점',
    location: '대구시 중구',
    createdAt: '2024-01-25',
  },
];

export const projects: Project[] = [
  {
    id: '1',
    title: '카페 인스타그램 마케팅',
    description: '신규 오픈한 카페의 인스타그램 계정 운영 및 마케팅 전략을 수립해주세요. 젊은 고객층을 타겟으로 하며, 카페의 분위기와 메뉴를 효과적으로 어필하고 싶습니다.',
    budget: 2000000,
    duration: '2개월',
    requirements: ['인스타그램 계정 설정', '콘텐츠 제작', '해시태그 전략', '광고 운영'],
    businessOwnerId: '1',
    businessOwnerName: '홍길동',
    businessName: '홍대 원두카페',
    status: 'open',
    createdAt: '2024-03-01',
    deadline: '2024-05-01',
  },
  {
    id: '2',
    title: '뷰티샵 온라인 마케팅',
    description: '기존 뷰티샵의 온라인 마케팅을 강화하고 싶습니다. 네이버 블로그, 구글 광고 등을 활용한 종합적인 마케팅 전략이 필요합니다.',
    budget: 3000000,
    duration: '3개월',
    requirements: ['네이버 블로그 운영', '구글 광고', 'SEO 최적화', '고객 후기 관리'],
    businessOwnerId: '2',
    businessOwnerName: '김영희',
    businessName: '영희네 뷰티샵',
    status: 'in_progress',
    expertId: '2',
    expertName: '박디지털',
    createdAt: '2024-02-20',
    deadline: '2024-05-20',
  },
  {
    id: '3',
    title: '한식당 브랜딩 및 마케팅',
    description: '전통 한식당의 브랜드 이미지를 개선하고 젊은 층에게도 어필할 수 있는 마케팅 전략을 수립해주세요.',
    budget: 2500000,
    duration: '1개월',
    requirements: ['브랜드 컨셉 설정', '로고 디자인 피드백', 'SNS 마케팅', '메뉴 사진 촬영 기획'],
    businessOwnerId: '3',
    businessOwnerName: '박철수',
    businessName: '철수네 한식당',
    status: 'completed',
    expertId: '1',
    expertName: '김마케팅',
    createdAt: '2024-01-30',
    deadline: '2024-02-28',
  },
  {
    id: '4',
    title: '온라인 쇼핑몰 마케팅',
    description: '의류 온라인 쇼핑몰의 매출 증대를 위한 마케팅 전략이 필요합니다. 특히 20-30대 여성을 타겟으로 합니다.',
    budget: 4000000,
    duration: '3개월',
    requirements: ['타겟 고객 분석', '광고 캠페인 기획', '인플루언서 마케팅', '전환률 최적화'],
    businessOwnerId: '1',
    businessOwnerName: '홍길동',
    businessName: '홍대 패션샵',
    status: 'open',
    createdAt: '2024-03-05',
    deadline: '2024-06-05',
  },
  {
    id: '5',
    title: '헬스장 회원 모집 마케팅',
    description: '새로 오픈하는 헬스장의 회원 모집을 위한 마케팅 캠페인을 기획해주세요.',
    budget: 1500000,
    duration: '1개월',
    requirements: ['오픈 이벤트 기획', '지역 광고', 'SNS 마케팅', '체험권 마케팅'],
    businessOwnerId: '2',
    businessOwnerName: '김영희',
    businessName: '영희네 헬스클럽',
    status: 'open',
    createdAt: '2024-03-10',
    deadline: '2024-04-10',
  },
];

export const applications: Application[] = [
  {
    id: '1',
    projectId: '1',
    expertId: '4',
    expertName: '최소셜',
    message: '카페 인스타그램 마케팅에 관심이 많습니다. 젊은 층 타겟 마케팅에 특화되어 있어 프로젝트에 적합할 것 같습니다.',
    proposedRate: 35000,
    status: 'pending',
    createdAt: '2024-03-02',
  },
  {
    id: '2',
    projectId: '1',
    expertId: '1',
    expertName: '김마케팅',
    message: '카페 브랜딩과 SNS 마케팅 경험이 풍부합니다. 성공적인 프로젝트를 만들어보겠습니다.',
    proposedRate: 50000,
    status: 'pending',
    createdAt: '2024-03-03',
  },
  {
    id: '3',
    projectId: '4',
    expertId: '5',
    expertName: '정전략',
    message: '온라인 쇼핑몰 마케팅 전략 수립 경험이 많습니다. 전반적인 마케팅 방향성을 제시해드리겠습니다.',
    proposedRate: 70000,
    status: 'pending',
    createdAt: '2024-03-06',
  },
];

export const quotes: Quote[] = [
  {
    id: '1',
    projectId: '1',
    expertId: '4',
    expertName: '최소셜',
    expertRating: 4.5,
    expertExperience: 2,
    totalPrice: 1800000,
    estimatedDuration: '6주',
    workScope: [
      '인스타그램 계정 최적화',
      '콘텐츠 기획 및 제작 (주 3회)',
      '해시태그 전략 수립',
      '인스타그램 광고 운영',
      '월간 성과 리포트'
    ],
    deliverables: [
      '인스타그램 계정 셋업 가이드',
      '콘텐츠 달력 (2개월분)',
      '해시태그 리스트 100개',
      '광고 캠페인 설정',
      '월간 분석 리포트'
    ],
    message: '젊은 타겟층에 특화된 카페 마케팅 전략을 제안드립니다. 트렌디한 콘텐츠로 브랜드 인지도를 높이고 방문 고객을 늘려드리겠습니다.',
    timeline: [
      { phase: '1단계: 계정 최적화', duration: '1주', description: '프로필 설정, 브랜드 톤앤매너 구축' },
      { phase: '2단계: 콘텐츠 제작', duration: '4주', description: '정기 포스팅 및 스토리 제작' },
      { phase: '3단계: 광고 운영', duration: '1주', description: '타겟 광고 설정 및 최적화' }
    ],
    status: 'pending',
    createdAt: '2024-03-02',
    expiresAt: '2024-03-09',
  },
  {
    id: '2',
    projectId: '1',
    expertId: '1',
    expertName: '김마케팅',
    expertRating: 4.8,
    expertExperience: 5,
    totalPrice: 2200000,
    estimatedDuration: '8주',
    workScope: [
      '브랜드 아이덴티티 강화',
      '인스타그램 통합 마케팅',
      '오프라인 연계 이벤트',
      '인플루언서 협업',
      '고객 리뷰 관리'
    ],
    deliverables: [
      '브랜딩 가이드라인',
      'SNS 마케팅 전략서',
      '이벤트 기획안',
      '인플루언서 DB',
      '고객 관리 시스템'
    ],
    message: '단순 SNS 운영을 넘어 브랜드 전체의 마케팅 전략을 수립해드립니다. 오프라인과 온라인을 연계한 통합 마케팅으로 확실한 성과를 만들어드리겠습니다.',
    timeline: [
      { phase: '1단계: 브랜드 분석', duration: '2주', description: '현황 분석 및 전략 수립' },
      { phase: '2단계: 콘텐츠 실행', duration: '4주', description: 'SNS 운영 및 이벤트 진행' },
      { phase: '3단계: 성과 최적화', duration: '2주', description: '데이터 분석 및 전략 보완' }
    ],
    status: 'pending',
    createdAt: '2024-03-03',
    expiresAt: '2024-03-10',
  },
  {
    id: '3',
    projectId: '1',
    expertId: '3',
    expertName: '이콘텐츠',
    expertRating: 4.9,
    expertExperience: 4,
    totalPrice: 1600000,
    estimatedDuration: '7주',
    workScope: [
      '콘텐츠 SEO 최적화',
      '블로그 연계 마케팅',
      '검색엔진 최적화',
      '로컬 SEO',
      '온라인 리뷰 관리'
    ],
    deliverables: [
      'SEO 키워드 리스트',
      '블로그 콘텐츠 10개',
      '구글 마이비즈니스 최적화',
      '리뷰 관리 가이드',
      'SEO 성과 리포트'
    ],
    message: '검색을 통한 자연스러운 고객 유입에 집중한 마케팅을 제안합니다. 지속가능하고 비용효율적인 마케팅 전략으로 장기적 성과를 만들어드리겠습니다.',
    timeline: [
      { phase: '1단계: SEO 분석', duration: '1주', description: '키워드 조사 및 경쟁사 분석' },
      { phase: '2단계: 콘텐츠 제작', duration: '5주', description: '블로그 및 SNS 콘텐츠 제작' },
      { phase: '3단계: 최적화', duration: '1주', description: '성과 측정 및 개선사항 도출' }
    ],
    status: 'pending',
    createdAt: '2024-03-04',
    expiresAt: '2024-03-11',
  },
  {
    id: '4',
    projectId: '4',
    expertId: '5',
    expertName: '정전략',
    expertRating: 5.0,
    expertExperience: 7,
    totalPrice: 3500000,
    estimatedDuration: '10주',
    workScope: [
      '전체 마케팅 전략 수립',
      '브랜드 포지셔닝',
      '고객 여정 분석',
      '멀티채널 마케팅',
      '성과 측정 시스템'
    ],
    deliverables: [
      '마케팅 전략서',
      '브랜드 가이드북',
      '고객 페르소나',
      '채널별 실행 계획',
      'KPI 대시보드'
    ],
    message: '온라인 쇼핑몰 성공을 위한 종합적인 마케팅 전략을 제시합니다. 체계적인 분석을 바탕으로 ROI를 극대화하는 마케팅 시스템을 구축해드리겠습니다.',
    timeline: [
      { phase: '1단계: 전략 수립', duration: '3주', description: '시장 분석 및 전략 설계' },
      { phase: '2단계: 실행 준비', duration: '2주', description: '시스템 구축 및 콘텐츠 준비' },
      { phase: '3단계: 캠페인 실행', duration: '5주', description: '마케팅 캠페인 운영 및 최적화' }
    ],
    status: 'pending',
    createdAt: '2024-03-06',
    expiresAt: '2024-03-13',
  },
];

// 마자영 캐시 데이터
export const cashBalances: MajayoungCash[] = [
  {
    userId: '1', // 김마케팅
    balance: 13000,
    totalEarned: 5000,
    totalSpent: 12000,
    lastUpdated: '2024-03-12',
  },
  {
    userId: '2', // 박디지털
    balance: 8500,
    totalEarned: 3000,
    totalSpent: 4500,
    lastUpdated: '2024-03-11',
  },
  {
    userId: '3', // 이콘텐츠
    balance: 25000,
    totalEarned: 0,
    totalSpent: 0,
    lastUpdated: '2024-03-10',
  },
  {
    userId: '4', // 최소셜
    balance: 6000,
    totalEarned: 2000,
    totalSpent: 6000,
    lastUpdated: '2024-03-12',
  },
  {
    userId: '5', // 정전략
    balance: 45000,
    totalEarned: 10000,
    totalSpent: 15000,
    lastUpdated: '2024-03-12',
  },
];

// 캐시 거래 내역
export const cashTransactions: CashTransaction[] = [
  {
    id: '1',
    userId: '1',
    type: 'spend',
    amount: -2000,
    description: '카페 인스타그램 마케팅 견적 발송',
    relatedId: '1',
    balanceAfter: 13000,
    createdAt: '2024-03-12T10:30:00Z',
    status: 'completed',
  },
  {
    id: '2',
    userId: '1',
    type: 'charge',
    amount: 20000,
    description: '마자영 캐시 충전 (기본 패키지)',
    balanceAfter: 15000,
    createdAt: '2024-03-10T14:20:00Z',
    status: 'completed',
  },
  {
    id: '3',
    userId: '4',
    type: 'spend',
    amount: -2000,
    description: '카페 인스타그램 마케팅 견적 발송',
    relatedId: '1',
    balanceAfter: 6000,
    createdAt: '2024-03-02T09:15:00Z',
    status: 'completed',
  },
  {
    id: '4',
    userId: '4',
    type: 'bonus',
    amount: 2000,
    description: '첫 견적 발송 보너스',
    balanceAfter: 8000,
    createdAt: '2024-03-01T16:45:00Z',
    status: 'completed',
  },
  {
    id: '5',
    userId: '5',
    type: 'spend',
    amount: -2000,
    description: '온라인 쇼핑몰 마케팅 견적 발송',
    relatedId: '4',
    balanceAfter: 45000,
    createdAt: '2024-03-06T13:20:00Z',
    status: 'completed',
  },
  {
    id: '6',
    userId: '3',
    type: 'charge',
    amount: 25000,
    description: '마자영 캐시 충전 (스타트 패키지)',
    balanceAfter: 25000,
    createdAt: '2024-03-10T11:30:00Z',
    status: 'completed',
  },
];

// 캐시 충전 패키지
export const cashPackages: CashPackage[] = [
  {
    id: '1',
    name: '기본 패키지',
    amount: 20000,
    price: 22000,
    bonusAmount: 0,
    description: '견적 10회 발송 가능',
    isActive: true,
  },
  {
    id: '2',
    name: '스타트 패키지',
    amount: 50000,
    price: 50000,
    bonusAmount: 5000,
    description: '견적 25회 발송 + 보너스 2회',
    isPopular: true,
    isActive: true,
  },
  {
    id: '3',
    name: '프로 패키지',
    amount: 100000,
    price: 95000,
    bonusAmount: 15000,
    description: '견적 50회 발송 + 보너스 7회',
    isActive: true,
  },
  {
    id: '4',
    name: '비즈니스 패키지',
    amount: 200000,
    price: 180000,
    bonusAmount: 40000,
    description: '견적 100회 발송 + 보너스 20회',
    isActive: true,
  },
];

// 결제 수단
export const paymentMethods: PaymentMethod[] = [
  {
    id: '1',
    name: '신용/체크카드',
    type: 'card',
    icon: '💳',
    isActive: true,
  },
  {
    id: '2',
    name: '계좌이체',
    type: 'bank',
    icon: '🏦',
    isActive: true,
  },
  {
    id: '3',
    name: '카카오페이',
    type: 'kakao',
    icon: '💛',
    isActive: true,
  },
  {
    id: '4',
    name: '네이버페이',
    type: 'naver',
    icon: '💚',
    isActive: true,
  },
];